global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'profitzen-identity'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: /metrics

  - job_name: 'profitzen-inventory'
    static_configs:
      - targets: ['host.docker.internal:5001']
    metrics_path: /metrics

  - job_name: 'profitzen-sales'
    static_configs:
      - targets: ['host.docker.internal:5002']
    metrics_path: /metrics

  - job_name: 'profitzen-analytics'
    static_configs:
      - targets: ['host.docker.internal:5004']
    metrics_path: /metrics

  - job_name: 'profitzen-product'
    static_configs:
      - targets: ['host.docker.internal:5005']
    metrics_path: /metrics

  - job_name: 'profitzen-customer'
    static_configs:
      - targets: ['host.docker.internal:5006']
    metrics_path: /metrics

  - job_name: 'profitzen-configuration'
    static_configs:
      - targets: ['host.docker.internal:5007']
    metrics_path: /metrics

  - job_name: 'profitzen-paymentmethods'
    static_configs:
      - targets: ['host.docker.internal:5008']
    metrics_path: /metrics

  - job_name: 'profitzen-gateway'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics
