CREATE USER identity_user WITH PASSWORD 'dev_password_123';
CREATE SCHEMA identity AUTHORIZATION identity_user;
GRANT USAGE ON SCHEMA identity TO identity_user;
GRANT CREATE ON SCHEMA identity TO identity_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA identity TO identity_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA identity TO identity_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT ALL ON TABLES TO identity_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT ALL ON SEQUENCES TO identity_user;

CREATE USER inventory_user WITH PASSWORD 'dev_password_123';
CREATE SCHEMA inventory AUTHORIZATION inventory_user;
GRANT USAGE ON SCHEMA inventory TO inventory_user;
GRANT CREATE ON SCHEMA inventory TO inventory_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA inventory TO inventory_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA inventory TO inventory_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT ALL ON TABLES TO inventory_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT ALL ON SEQUENCES TO inventory_user;

CREATE USER sales_user WITH PASSWORD 'dev_password_123';
CREATE SCHEMA sales AUTHORIZATION sales_user;
GRANT USAGE ON SCHEMA sales TO sales_user;
GRANT CREATE ON SCHEMA sales TO sales_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sales TO sales_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sales TO sales_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales GRANT ALL ON TABLES TO sales_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales GRANT ALL ON SEQUENCES TO sales_user;

CREATE USER products_user WITH PASSWORD 'dev_password_123';
CREATE SCHEMA products AUTHORIZATION products_user;
GRANT USAGE ON SCHEMA products TO products_user;
GRANT CREATE ON SCHEMA products TO products_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA products TO products_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA products TO products_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA products GRANT ALL ON TABLES TO products_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA products GRANT ALL ON SEQUENCES TO products_user;

CREATE USER analytics_user WITH PASSWORD 'dev_password_123';
CREATE SCHEMA analytics AUTHORIZATION analytics_user;
GRANT USAGE ON SCHEMA analytics TO analytics_user;
GRANT CREATE ON SCHEMA analytics TO analytics_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO analytics_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA analytics TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL ON TABLES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL ON SEQUENCES TO analytics_user;

GRANT USAGE ON SCHEMA sales TO analytics_user;
GRANT SELECT ON ALL TABLES IN SCHEMA sales TO analytics_user;
GRANT USAGE ON SCHEMA inventory TO analytics_user;
GRANT SELECT ON ALL TABLES IN SCHEMA inventory TO analytics_user;
GRANT USAGE ON SCHEMA products TO analytics_user;
GRANT SELECT ON ALL TABLES IN SCHEMA products TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales GRANT SELECT ON TABLES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT SELECT ON TABLES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA products GRANT SELECT ON TABLES TO analytics_user;