// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profitzen.Identity.Infrastructure;

#nullable disable

namespace Profitzen.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260123042754_AddPermissionsTable")]
    partial class AddPermissionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "identity");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId", "IsUsed");

                    b.ToTable("PasswordResetTokens", "identity");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.RoleModulePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Role", "Module")
                        .IsUnique();

                    b.ToTable("RoleModulePermissions", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("657d8739-67f1-4095-8284-84d6a666fa08"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3741),
                            Module = "dashboard",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("ec9bff63-46e7-45fc-b552-261e4307f3aa"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3749),
                            Module = "pos",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("da95c398-806d-4c86-b095-81be5df8b300"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3751),
                            Module = "sales",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("2b6251fe-9ecf-42c8-9867-d5fb3c8eebf0"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3752),
                            Module = "products",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("f14e5eb4-d6a0-4bfa-af53-1e1b2ad27f7c"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3755),
                            Module = "inventory",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("abf1b681-60bc-47f4-bfc0-9ccc7dbcb260"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3758),
                            Module = "purchases",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("c3c91b97-dc24-404d-a5a2-b8ebcba1bd9c"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3759),
                            Module = "customers",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("1b94c326-45de-407e-8f92-e7c0141f4fa8"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3760),
                            Module = "stores",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("8e4c2e6a-0a70-43a2-a580-714637b1cfc8"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3763),
                            Module = "users",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("a1f7a06a-3dc1-4dbc-95d2-5d4ee80540cb"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3765),
                            Module = "settings",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0ecd91e3-4e2a-40b8-a29d-5c6482d76e63"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3766),
                            Module = "dashboard",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f8f80d21-753d-4a30-93c6-fdf8f82135f3"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3768),
                            Module = "pos",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("39660bd0-4a2a-47ae-96fa-36a0440e280b"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3771),
                            Module = "sales",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("051b320d-70df-4814-9b97-522b0ae25430"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3772),
                            Module = "products",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("cd709560-2b1d-4586-9c9a-f0b93ecee3d2"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3773),
                            Module = "inventory",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("05ceffae-01c5-4378-b24d-2a24926e3c7e"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3775),
                            Module = "purchases",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("632e236e-cb7f-4113-8816-cb173b062dcf"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3777),
                            Module = "customers",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("5eb60ab3-b834-4074-a4ee-0ecd7bc8fef4"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3779),
                            Module = "stores",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("df5a3f0f-bbd8-45ae-a3a7-7e192f0e76e5"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3781),
                            Module = "dashboard",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("9ae23945-57d3-437e-8306-2677de570c41"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3783),
                            Module = "pos",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("57c3d396-15e5-499f-93d2-c121d50c76b2"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3785),
                            Module = "sales",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("200c292c-3ac7-490e-bfc2-94e8a4e56661"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3787),
                            Module = "customers",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("29ce08c5-d84e-4745-a27b-97c899b03a90"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3788),
                            Module = "dashboard",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("1962521f-4655-463c-b835-a3fc69c6cbe9"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3790),
                            Module = "products",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("29d14af2-7771-457c-8a99-8b8fbf38c932"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3793),
                            Module = "inventory",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("d637d2db-3804-4113-9045-e2b1e17973b2"),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 27, 54, 265, DateTimeKind.Utc).AddTicks(3794),
                            Module = "purchases",
                            Role = 8
                        });
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Stores", "identity");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.ToTable("Tenants", "identity");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", "identity");
                });

            modelBuilder.Entity("StoreUser", b =>
                {
                    b.Property<Guid>("StoresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("StoresId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserStores", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.User", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StoreUser", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.Store", null)
                        .WithMany()
                        .HasForeignKey("StoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
