// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profitzen.Identity.Infrastructure;

#nullable disable

namespace Profitzen.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260202052652_CreateAppModulesTable")]
    partial class CreateAppModulesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "identity");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.AppModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleInMenu")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("AppModules", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4488ea47-8a77-4878-b39a-2c7f83fbf7cb"),
                            Code = "dashboard",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3727),
                            GroupName = "PRINCIPAL",
                            Icon = "LayoutDashboard",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Dashboard",
                            Route = "/dashboard",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("2fcb3367-4ed7-4423-873f-64dadb7aec0f"),
                            Code = "pos",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3734),
                            GroupName = "PRINCIPAL",
                            Icon = "ShoppingCart",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Punto de Venta",
                            Route = "/pos",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("2bd9c723-0b58-4dc9-abb2-6d4422619464"),
                            Code = "sales_parent",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3738),
                            GroupName = "VENTAS",
                            Icon = "FileText",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Ventas",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a8f9c625-bd4c-4819-8bd6-8331f079115f"),
                            Code = "sales",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3739),
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Historial",
                            ParentId = new Guid("2bd9c723-0b58-4dc9-abb2-6d4422619464"),
                            Route = "/sales",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b411c1de-2227-43b2-a9f3-86dd7873253b"),
                            Code = "customers",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3743),
                            Icon = "Users",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Clientes",
                            ParentId = new Guid("2bd9c723-0b58-4dc9-abb2-6d4422619464"),
                            Route = "/customers",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a081ce79-7e3c-492f-bbfb-e7e717716303"),
                            Code = "intelligence_parent",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3747),
                            GroupName = "INTELIGENCIA",
                            Icon = "BarChart3",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Inteligencia",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("0db15d96-96dc-4115-9a94-86c8d4ee261a"),
                            Code = "analytics",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3750),
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Centro Analítico",
                            ParentId = new Guid("a081ce79-7e3c-492f-bbfb-e7e717716303"),
                            Route = "/analytics",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("78b2c716-abba-4045-a55a-8de7ffbe16c5"),
                            Code = "analytics_ia",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3752),
                            Icon = "BrainCircuit",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Analizador IA",
                            ParentId = new Guid("a081ce79-7e3c-492f-bbfb-e7e717716303"),
                            Route = "/analytics/ia",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a2df166b-151a-4278-b845-d0b93d8668f1"),
                            Code = "analytics_ia_history",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3757),
                            Icon = "Clock",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Bitácora de IA",
                            ParentId = new Guid("a081ce79-7e3c-492f-bbfb-e7e717716303"),
                            Route = "/analytics/ia/vigilante/history",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("bbb90069-7edb-4303-8cf4-b893816cec6e"),
                            Code = "operations_parent",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3760),
                            GroupName = "OPERACIONES",
                            Icon = "Package",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Operaciones",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("e61dafa8-44b3-4fca-b720-a86990225f3a"),
                            Code = "products",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3763),
                            Icon = "Tags",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Productos",
                            ParentId = new Guid("bbb90069-7edb-4303-8cf4-b893816cec6e"),
                            Route = "/products",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("6a054434-f504-49fc-8f5f-a2dd428621e5"),
                            Code = "inventory",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3765),
                            Icon = "Package",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Inventario",
                            ParentId = new Guid("bbb90069-7edb-4303-8cf4-b893816cec6e"),
                            Route = "/inventory",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("74cc5733-8e8a-4ba5-bc0b-2477b44570fa"),
                            Code = "purchases",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3769),
                            Icon = "CreditCard",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Compras",
                            ParentId = new Guid("bbb90069-7edb-4303-8cf4-b893816cec6e"),
                            Route = "/purchases",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("646920b6-1c89-477f-b1bd-6a57cfeafefc"),
                            Code = "suppliers",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3771),
                            Icon = "Truck",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Proveedores",
                            ParentId = new Guid("bbb90069-7edb-4303-8cf4-b893816cec6e"),
                            Route = "/suppliers",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("0a883f5c-54ae-4363-b837-f5f002156652"),
                            Code = "stores",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3773),
                            GroupName = "PRINCIPAL",
                            Icon = "Store",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Sucursales",
                            Route = "/stores",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("6900dcbe-e23e-4528-8438-5a1eb319eded"),
                            Code = "settings",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3775),
                            GroupName = "CONFIGURACION",
                            Icon = "Store",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Mi Empresa",
                            Route = "/settings",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("f777c999-9d8b-44a3-aa1b-aa8b48ebccf1"),
                            Code = "users",
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3780),
                            GroupName = "CONFIGURACION",
                            Icon = "UserCog",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Usuarios y Roles",
                            Route = "/users",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId", "IsUsed");

                    b.ToTable("PasswordResetTokens", "identity");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.RoleModulePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Role", "Module")
                        .IsUnique();

                    b.ToTable("RoleModulePermissions", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f34dcfd3-f9f0-4595-bba3-a04d38cb3969"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3898),
                            Module = "dashboard",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("29216595-1ab3-48fc-a4db-b47c3c320004"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3901),
                            Module = "pos",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("13b8cf3e-7d2e-4f1d-afd5-c222671193ab"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3903),
                            Module = "sales_parent",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("68965ac2-5c63-450a-af0f-7a535f209139"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3907),
                            Module = "sales",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("9c860b1c-2208-4e6f-b496-fb7d0cfe9f75"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3908),
                            Module = "customers",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0b60f1a4-5da0-4508-bada-cc0acf5e49be"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3910),
                            Module = "intelligence_parent",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("746ec9d9-d039-46d9-b524-d4681297a31c"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3911),
                            Module = "analytics",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("89af7095-04f3-4767-8fa7-146d7b091c9b"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3914),
                            Module = "analytics_ia",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("d30999bc-3a0f-42c7-a7ba-991b2d3e7e83"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3915),
                            Module = "analytics_ia_history",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("3be9b082-d586-4b45-a8fc-4a4f70f1746d"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3917),
                            Module = "operations_parent",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("ffc86804-3424-4ec5-ae5e-a855855e1a1d"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3919),
                            Module = "products",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("f0cd353a-ecab-4914-ab04-a333c1541195"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3921),
                            Module = "inventory",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("96ab3f47-914f-45e8-b4e0-7ddb66507352"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3923),
                            Module = "purchases",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("116ba26d-847f-4e28-8855-56863c0c2e36"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3924),
                            Module = "suppliers",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("b61341ea-9170-4a94-ab2d-950469ac01e6"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3925),
                            Module = "stores",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("4e1659f9-4e1c-4a59-8ac0-250d9276a83d"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3928),
                            Module = "settings",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("d50f1bc7-0398-46bf-a0c3-1f25b2265274"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(3929),
                            Module = "users",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0c3bf41c-ae9a-4456-baf5-7493129d7721"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4013),
                            Module = "dashboard",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("173827c4-5e24-4079-8b99-e696c7d1acec"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4016),
                            Module = "pos",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("bd4e8842-2e28-42ca-b259-6b93b037e0c7"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4019),
                            Module = "sales_parent",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("274c95cc-c4a7-45ff-a460-e1b58334f831"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4021),
                            Module = "sales",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("ce1613a3-e431-4cdf-af7f-32def029aaaa"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4022),
                            Module = "customers",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d25029ff-2172-46cc-9caa-96662f8b0ade"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4023),
                            Module = "intelligence_parent",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("4ab86fe6-7fdc-41e0-9d12-bfa587c047bc"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4026),
                            Module = "analytics",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f1f32a89-1745-4e87-b2d6-4a7f1b1c816b"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4027),
                            Module = "analytics_ia",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("5386bb5c-75c8-48b8-b2f9-c4c869baa491"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4028),
                            Module = "analytics_ia_history",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f9fdfec7-9dd5-43e3-a6c7-7f1c27a70656"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4030),
                            Module = "operations_parent",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("0d3fd2cf-8465-4d91-ac55-cdc982dd74fd"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4033),
                            Module = "products",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("8aafeb9e-d938-4b9e-ba58-ec99b0abed66"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4034),
                            Module = "inventory",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("4f722e6b-4665-423f-9012-14adf02dd115"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4035),
                            Module = "purchases",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("51cca1b0-6bbf-4f16-bb70-208bdf6319ea"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4036),
                            Module = "suppliers",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("e601f6f2-9a46-4e23-94da-f54247271b35"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4039),
                            Module = "stores",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("6863840c-4919-44ee-a10f-6f96f302d95c"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4041),
                            Module = "pos",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("8152e660-862b-44d9-a127-51ace4a5608f"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4044),
                            Module = "customers",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("c5b34699-592d-4ad4-be74-ed6e7a8f99b9"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4046),
                            Module = "products",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("44535eb2-1761-42db-a5f2-fee2c2212918"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4049),
                            Module = "inventory",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("6a1b0fd3-7cae-47b7-a2db-c51e9573b752"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4051),
                            Module = "purchases",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("6e03fc25-ed07-4a89-992f-ddf39a6f9e6b"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4052),
                            Module = "suppliers",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("c7a164b3-8566-4d51-9e3f-766a859bdbcb"),
                            CreatedAt = new DateTime(2026, 2, 2, 5, 26, 51, 762, DateTimeKind.Utc).AddTicks(4053),
                            Module = "operations_parent",
                            Role = 8
                        });
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Stores", "identity");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.ToTable("Tenants", "identity");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", "identity");
                });

            modelBuilder.Entity("StoreUser", b =>
                {
                    b.Property<Guid>("StoresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("StoresId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserStores", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.AppModule", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.AppModule", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.User", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StoreUser", b =>
                {
                    b.HasOne("Profitzen.Identity.Domain.Entities.Store", null)
                        .WithMany()
                        .HasForeignKey("StoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Profitzen.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Profitzen.Identity.Domain.Entities.AppModule", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
